
POST http://localhost:3000/api/auth/signup HTTP/1.1
 Content-Type: application/json

{
    "email":"bnbgmail.com",
    "password": "testTEST12"
}
###
POST http://localhost:3000/api/auth/login HTTP/1.1
Content-Type: application/json


{
    "email":"test6@gmail.com",
    "password": "test"
}
###
POST http://localhost:3000/api/sauces HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTg1MmVjYjcxM2IxNWRmODBhNmRjNzAiLCJpYXQiOjE2MzYxMjI5MjcsImV4cCI6MTYzNjIwOTMyN30.zFcKHl6aBIrZI5LvO_rv6LrKZXfloqJs4mFegQrK5SE


{
    "userId": "6181073c481f651c2ffcdd6f",
    "name":"ketchup" ,
  "manufacturer":"heintz" ,
  "description":"rouge" ,
  "mainPepper":"piment" ,
  "imageUrl": "url",
  "heat": 1,
  "likes": 1,
  "dislikes": 8,
  "usersLiked": [],
  "usersDislikes": []
}
###
GET http://localhost:3000/api/sauces HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTkyM2RlNDM2Y2NmYjJmOGVkYWViYmIiLCJpYXQiOjE2MzY5NzQwNzAsImV4cCI6MTYzNzA2MDQ3MH0.Bo36uBULmU_081XILd4fG66GBAY5oe9esOAGXtt763w
###
GET http://localhost:3000/api/sauces/61852f51a2b6dce0a9033f45 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTg1MmVjYjcxM2IxNWRmODBhNmRjNzAiLCJpYXQiOjE2MzYzNzk5NzcsImV4cCI6MTYzNjQ2NjM3N30.CrIQ3SdgP8nIQWt6_6kHTlvfFiqDwXUdWT1WROvwA70
###
PUT http://localhost:3000/api/sauces/61810b0fb421cf9bf61bded8 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTgxMDczYzQ4MWY2NTFjMmZmY2RkNmYiLCJpYXQiOjE2MzU5MzExMzAsImV4cCI6MTYzNjAxNzUzMH0.ToGT9fg0cuDmQ8ujIr56DtRJpo_nZFBdDv1ONPcmVSI

{
    "userId": "6181073c481f651c2ffcdd6f",
    "name":"bourguignone" ,
  "manufacturer":"amora" ,
  "description":"orange" ,
  "mainPepper":"tomate" ,
  "imageUrl": "url",
  "heat": 8,
  "likes": 3,
  "dislikes": 8,
  "usersLiked": [],
  "usersDislikes": []
}
###
DELETE http://localhost:3000/api/sauces/61810b0fb421cf9bf61bded8 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTgxMDczYzQ4MWY2NTFjMmZmY2RkNmYiLCJpYXQiOjE2MzU5MzExMzAsImV4cCI6MTYzNjAxNzUzMH0.ToGT9fg0cuDmQ8ujIr56DtRJpo_nZFBdDv1ONPcmVSI